<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  
<html xmlns="http://www.w3.org/1999/xhtml">  
  <head>  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/stylesheets/screen.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="alternate"	type="application/atom+xml" title="Johan Nilssons Photos" href="/photos/list/format/atom">
    <title><?= $this->title ?> - Johan Nilssons Photos</title>
  </head>
  <body>
  <div id="main">
    <h1><a href="<?= $this->url(array(), 'photos_path'); ?>">Johan Nilssons Photos</a></h1>
	<?= $this->layout()->content; ?>  
    <div class="bottom">
        <p><a href="/photos/">List</a>
        <a href="/archives/">Archive</a>
        <a href="http://gitorious.org/projects/yag/">Get the source</a></p>
    </div>
  </div>
  <?= $this->analytics() ?>
  </body>  
</html>
