<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  
<html xmlns="http://www.w3.org/1999/xhtml">  
  <head>  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/stylesheets/screen.css" media="screen" rel="stylesheet" type="text/css" />
    <title>YAG</title>
  </head>  
  <body>  
  <h1>YAG</h1>
  <div id="main">
	<?php echo $this->layout()->content; ?>  
  </div>
  </body>  
</html>
