<div id="content">
    <div class="photo">
        <h2><?php echo $this->photo->title ?></h2>
        <p><?php echo $this->partial('_photo.phtml', array('photo' => $this->photo, 'style' => 'medium')) ?></p>
        <p><?php echo $this->photo->description ?></p>
    </div>
</div>

<div id="sidebar">
    <?php echo $this->photoStream($this->photo) ?> 

    <?php if (count($this->tags) > 0) :?>
    <h4>Tags</h4>
    <ul>
    <?php foreach ($this->tags as $tag) :?>
        <li><a href="<?php echo $this->url(array('name' => $tag->name), 'tags-name'); ?>"><?php echo $tag->name ?></a></li>
    <?php endforeach;?>
    </ul>
    <?php endif;?>

    <?php //echo $this->partial('_map.phtml', array('photo' => $this->photo));?>
    <?php echo $this->map($this->photo) ?>
</div>
