<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?= $this->apiKey ?>" type="text/javascript"></script>

<script type="text/javascript">
//<![CDATA[
function load() {
    if (GBrowserIsCompatible()) {
        var map = new GMap2(document.getElementById("map"));
        var point = new GLatLng(<?= $this->latitude ?>, <?= $this->longitude?>);
        map.setCenter(point, 15);
        var marker = new GMarker(point);
        map.addOverlay(marker);
    }
}
window.onload=function() {
    load();
}
window.onunload=function() {
    GUnload();
}
//]]>
</script>
    <div id="map" style="width: 250px; height: 200px"></div>
