<div id="content">
    <div class="photo">
        <h2><?= $this->photo->title ?></h2>
        <p><?= $this->partial('_photo.phtml', array('photo' => $this->photo, 'style' => 'medium')) ?></p>
        <p><?= $this->photo->description ?></p>
    </div>
</div>

<div id="sidebar">
    <?= $this->photoStream($this->photo) ?> 
    <?= $this->photoTags($this->photo) ?>
    <h4>Additional Information</h4>
    <ul class="details">
        <li>Taken on <?= $this->date($this->photo->taken_on) ?></li>
        <li>Taken with a <?= $this->photo->make ?> <?= $this->photo->model ?></li>
        <?php if ($this->auth->hasIdentity()) :?>
        <li><a href="<?= $this->url(array('id' => $this->photo->id), 'photos_edit_path') ?>">Edit</a></li>
        <?php endif?>
    </ul>

    <?= $this->map($this->photo) ?>
</div>
