<div id="content">
    <div class="photo">
        <h2><?php echo $this->photo->title ?></h2>
        <p><?php echo $this->partial('_photo.phtml', array('photo' => $this->photo, 'style' => 'medium')) ?></p>
        <p><?php echo $this->photo->description ?></p>
    </div>
</div>

<div id="sidebar">
    <?= $this->photoStream($this->photo) ?> 
    <?= $this->photoTags($this->photo) ?>
    <?= $this->map($this->photo) ?>
</div>
