<ul class="archive">
<?php foreach ($this->archive as $year => $months) :?>
    <li>
        <a href="<?= $this->url(array('year' => $year), 'archives_list_path') ?>"><?= $year ?></a>
        <ul>

            <?php foreach ($months as $month => $count) :?>
            <li><a href="<?= $this->url(array('year' => $year, 'month' => $month), 'archives_list_month_path') ?>"><?= $month ?></a> (<?= $count ?>)</li>
            <?php endforeach; ?>

        </ul>
    </li>
<?php endforeach; ?>
</ul>
