<?php echo "<?xml version=\"1.0\" encoding=\"utf-8\" ?>";?>

<feed xmlns="http://purl.org/atom/ns#">
    <link type="application/x.atom+xml" rel="service.post" href="<?= $this->url?>/atom/upload/" title="Post to Yag" />
    <link type="application/x.atom+xml" rel='service.feed' href="<?= $this->url?>/photo/list/format/atom/" title="Feed" />
    <link type="text/html" rel='alternate' href="<?= $this->url?>/photos/list/" title="Show all photos" />
</feed>
